### ISSUE TITLE
Implement batch deletion of uploaded songs?

### ISSUE THREAD

**Issue by dairefagan** [jamesbrindle/YTMusicUploader#1]
Can you please implement batch deletion for songs?

**Comment by jamesbrindle** [comment]
Hi, I've got something in mind for batch deletions... I was thinking of a tick box for the functionality to 'Delete from YouTube Music When I Delete From My Music Library' option... Is that the kind of think you were thinking, or are you thinking more of a 'pick and choose' what to delete feature?

**Comment by dairefagan** [comment]
Basically I mistakenly synced my old Google Play Music library with bad ID3
tags, and some music I had for others. After some time I manually removed
all of the albums only to discover the individual songs are kept.

Checkboxes would be great, with a checkbox for select all at the top? There
are calls on reddit to be able to edit like this for (uploaded and not)
songs, albums, playlists etc, but right now I'm specifically concerned with
my uploaded songs.

**Comment by jamesbrindle** [comment]
I see what you mean... Yeah sounds like a plan... The 'delete from YT music when you delete from library' probably won't be sufficient then. It sort of relies on good ID3 tags... What I'd have to do is query all artists from uploaded music, then all songs for each artist. Might take a good few minutes to retrieve all the songs, but I it's definitely doable. I'll add it to my list.

**Comment by dairefagan** [comment]
Excellent, thank you.

Could you please post here whenever you get around to it?

**Comment by jamesbrindle** [comment]
Added ability to delete tracks and albums from YT Music via a new form that displays all song uploaded in a checkbox tree view, as well as reset the local DB.

**Comment by jamesbrindle** [comment]
Additional 'Manage YT Music' uploaded songs UI / Cache / Performance improvements and a couple of fixes in version 1.4.1
