### ISSUE TITLE
Handling of large FLAC files smaller than 300 MB

### ISSUE THREAD

**Issue by captiglo** [jamesbrindle/YTMusicUploader#13]
Hi James, now skipping of large FALC files works as expected, but now when YTMusicUploader tries to upload a full album FLAC file around 220 MB, it gets an upload error from google and it tries again, again and again..., so we are back in a loop. Maybe you should implemet something like: If the upload fails for a certain number of times, skip the file. It could be desirable to limit this behavior to FLAC files only or in general to files larger than 100MB. Just an idea.

**Comment by jamesbrindle** [comment]
Hey,

You've  highlighted a very good idea!

The initial reasoning behind the looping when it encounters errors was to battle YTMusic's occasional  '500' error, in the expectation that the file would eventually get uploaded. This obviously isn't the case for certain files that YT Music doesn't like.

I've implemented your suggestion... The application will still give a failed upload a few tries, and retry once more after the batch has batch has complete, but then won't keep trying.

Let's see how we get on with the new version here: https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.5.2

I found a good few bugs this time while digging into the code after not seeing it for a few weeks... Typically trying to solve one issue while creating another. Lets hope this version is better.

More details below:

### Retry on MainProcess When Issues Are Present

* When there are issues when uploading and the 'Issue' counter increments, then when all the uploads have finished, the application will once again try to upload the file it had an issue with previously in an attempt to work around YT Music's mysterious '500' error. 

* Unfortunately this ends up looping for quite some time if not forever, and the application never ends up in an 'idle' state. Therefore a limit of '1' has been put in place for how many times the application will loop through its issues on in the main application process (not to be confused with the n/5 attempts to upload while uploading is taking place which will remain the same).

* We do however want to retry the the failed upload at some point, for the following reasons:
    * YT Music may fix an issue at their end for 500'd-ing certain files
    * We may re-encode or compress the file and want to retry it

* Therefore, the file will once again attempt to upload in 30 days, or if the 'Issue' state of the file is reset via the 'Issues' report form.

**Comment by jamesbrindle** [comment]
Presumed OK now
