### ISSUE TITLE
The Music Manage section only displays the 23 first playlists in the alphabetical order

### ISSUE THREAD

**Issue by stgobin** [jamesbrindle/YTMusicUploader#20]
Hello,

I am new to YT Uploader. It looks interesting. Thank you for creating it.
When I go to the Music Manage section, I only see the 23 first playlists.  The following ones in the alphabetic order does not appear.
Is it a bug or am I doing something wrong?

Thank you in advance for letting me know.

Steve

![Capture](https://user-images.githubusercontent.com/78701915/107157460-7e454300-6984-11eb-8a67-e669d4ad4714.JPG)

**Comment by jamesbrindle** [comment]
Hey,

It could well be a bug, however there may be a couple of reasons why your playlists are missing.

1. Invalid playlist file type for YTM Uploader
2. The tracks within the playlist can't be found (which can happen if you say, move the tracks / folder somewhere else).

I doubt it's any of these reasons though...

Any chance you could put a couple of your playlists files here:

https://1drv.ms/u/s!At6EvCXZJAN60owsVVjlJh8IZYVqVw?e=l4hNcU

I can start but checking the validity of the files, and we can go from there... The playlist feature is relatively new, and so may have  a couple of bugs  yet to iron out.

Thanks.

Regards,

Jamie

**Comment by stgobin** [comment]
Hi James,

Thank you for your response.  Since only the 23 first playlists in their alphabetical order are visible, I presume that the problem comes from the 24th one, whose name is Feelin' Good in the 80s.  Could the problem come from the apostrophe sign in the list name.

That playlist is generated by YT Music, thus it's not one that I created.  I though it might be the cause of the problem but one of the playlists that are displayed, namely 80s Alternative Driving Anthems, is also generated by YT and it is displyed.

The the 24th list is generated by YT Music, I cannot export any file from it.
Thank you.

Best regards,

Steve

**Comment by jamesbrindle** [comment]
Hey, I've found the issue and uploaded a new version. Would you like to give it a try?

https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.6.7

Regards,

J

**Comment by stgobin** [comment]
Hi James,
Thank you for your work.
Unfortunately the playlist count is no stopping at N°48 while there are a few more.
In this case, the playlist that should appears at #49 is one I created myself and its name has no apostrophe.
I hope this helps.
Best regards,
Steve

**Comment by jamesbrindle** [comment]
I think I know why...

**Comment by stgobin** [comment]
Sorry for always answering with a bad news  while you spend a lot of time to improve the tool.  I hope at least that my feedback is helpful.
Thank you.
Steve

**Comment by jamesbrindle** [comment]
Hey,

No it's fine I appreciate people taking the time to give feedback. It's
very difficult to test just by myself.

Regards,

J

**Comment by jamesbrindle** [comment]
Hey Pal.

I believe I've finally fixed this now... 

Let me know how it goes 👍 

Regards,

J

**Comment by stgobin** [comment]
Hi James,
Yes, all playlists are now there.
Thank you.
Regards,
Steve
