### ISSUE TITLE
Annoying WebView2 error message on Windows 10 desktop

### ISSUE THREAD

**Issue by khdetwei** [jamesbrindle/YTMusicUploader#22]
Windows 10 now has a red box on the desktop that overlays the normal Microsoft Start button, can't be selected or hidden that says "WebView2 It looks like Canary Edge Core never finished installing".  Further details at the bottom of the red box - off the screen so it can't be seen (I copy/pasted it):  Please delete the folder: C:\Users\khdetwei\AppData\Local\YTMusicUploader\84.0.522.63 and then restart this application. If the error persists, then this application has been built wrong. Please see the 'WARNING' in file: 'Dialogues/ConnectToYTMusics.

**Comment by jamesbrindle** [comment]
Hey,

Yeah that's odd you shouldn't be getting that message, unless you've built from source?

Couple of questions:

1. Have you deleted the folder: C:\Users\khdetwei\AppData\Local\YTMusicUploader\84.0.522.63 and tried re-opening the application?

2. Have you built from source or used a release version?

3. What version are you on?

Regards,

J

**Comment by jamesbrindle** [comment]
Closed - No response
