### ISSUE TITLE
YT Music Uploader

### ISSUE THREAD

**Issue by dlkj07** [jamesbrindle/YTMusicUploader#23]
I did a quick search and couldn't find a solution...I can't resize the main YT Music Uploader interface. I've tried changing my resolution hoping it would help but it did not. I have a feeling this is a common problem and there's an easy solution but can't find it. :(  By the way, the "manage the uploaded music" screen does allow me to resize.

Thanks

**Comment by jamesbrindle** [comment]
That's very odd... You should most definitely be able to resize that form.

I don't suppose you've running an older version of Windows or a VM are you?

**Comment by jamesbrindle** [comment]
No response - closed
