### ISSUE TITLE
Mass reset of issues

### ISSUE THREAD

**Issue by riahc3** [jamesbrindle/YTMusicUploader#24]
Hello

I have a lot of music that was been marked as with issues but its A LOT so clearing them out ONE by ONE is a hassle.

Please add a tick so they can all be removed and a upload can be retried.

Thanks

**Comment by jamesbrindle** [comment]
Hey,

Anything files marked with 'issue' will be retried after 24 hour, or if you restart the application... ?

That being said, there are certain music files that simply can't be uploaded you YouTube music, such as files over 300MB, and for some reason certain .flac files... These however should be just ignored...

I wonder why you have so many issues?

Also, you can mass reset all music states in the 'YT Manager' form.

Regards,

J

**Comment by jamesbrindle** [comment]
I will add the option though it's not a big thing to do.

**Comment by riahc3** [comment]
Its my scenario. All the issues are normal.

The program is opened for more than 24 hours and I see issues dating back to Janurary

**Comment by riahc3** [comment]
> I will add the option though it's not a big thing to do.

Thank you very much.

**Comment by jamesbrindle** [comment]
Done: https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.7.2
