### ISSUE TITLE
Request: New Filter to YouTube Manage

### ISSUE THREAD

**Issue by missiah** [jamesbrindle/YTMusicUploader#26]
Hello,

first i wanna say thank you for your work, your tool looks pretty awesome.

I have a ton of music  sorted by Album Names.

Would it be possible to add a additional Filter for Albums?
Apparently i have not clean Tagged everything with Artists.

![Neue Bitmap](https://user-images.githubusercontent.com/57118418/121787091-6f85cb80-cbc4-11eb-8993-1cc1ab03f72f.jpg)

**Comment by jamesbrindle** [comment]
Hey,

You're quite welcome...

I will certainly have a look and see if it's feasible, although in this
instance I can't promise anything...

Thing is it's not meant to pre-fetch everything from YTM (i.e. albums and
songs). It pre-fetches the artists, then when you go to expand it does
another fetch for the alums and songs under the specifically selected
artist to keep it efficient.

Thinking aloud I could perhaps add a button to 'fetch all alums' Then you
could filter...

Leave it with me... Presently I'm enjoying the summer though  - When it
starts raining again (I live in England) I'll add some new feature and make
some tweaks.

Kind regards,

Jamie

**Comment by missiah** [comment]
Appreciate that,

I still wish sunny weather completely selflessly.
