### ISSUE TITLE
Appears to Have Issues Uploading Long Tracks

### ISSUE THREAD

**Issue by xcjs** [jamesbrindle/YTMusicUploader#3]
I received a 500 error while attempting to upload Symphony X's "The Odyssey" which is a 24 minute song.

**Comment by xcjs** [comment]
An additional note - this puts the file size at ~55.5 MB.

**Comment by jamesbrindle** [comment]
Hi. According to YouTube Music, the max file size is 300MB. So you shouldn't really have an issue uploading the 24 minute song? Please can you put the track here and I'll certainly have a look for you: https://1drv.ms/u/s!At6EvCXZJAN6zOl9uVwUrwG6xUidHw?e=1WDJWb 

Thanks for reporting the issue, much appreciated!

**Comment by xcjs** [comment]
@jamesbrindle I assumed it was the file size, but the file uploaded successfully the next time it was attempted. This issue can be closed.
