### ISSUE TITLE
Main Process thread error: Not a valid Win32 FileTime

### ISSUE THREAD

**Issue by kuraikaze** [jamesbrindle/YTMusicUploader#31]
I'm now getting the above error when I try to update my YTM library from my local NAS source.
I'm not convinced it's an issue with your app, as such, but possibly an issue with a file being scanned.
(Checked all .NET components updated, downgraded to previous known-good YTMU versions, tried x86 instead of x64 versions, installed on different machine, tried accessing source path as UNC share \\Server\Music instead of mapped X:\Music etc etc.)
I get the same critical error no matter what I try.

It therefore seems possible that a new addition to the NAS Music store has a messed up date value.

Is there any logging/debug mode I can set to see if a particular file is causing the issue ?

Log snippet below - full log available if required.

```
<YTMUploader-Log>

    <Event>2021-09-18T15:22:07.3715316+01:00</Event>

    <LogTypeId>4</LogTypeId>

    <Machine>VAGUE-VM</Machine>

    <Source>FromFileTimeUtc</Source>

    <Message>Main Process thread error: Not a valid Win32 FileTime.

Parameter name: fileTime</Message>

    <Version>1.8.0</Version>

    <StackTrace>   at System.DateTime.FromFileTimeUtc(Int64 fileTime)

   at JBToolkit.Windows.FileData.ConvertDateTime(UInt32 high, UInt32 low)

   at JBToolkit.Windows.FileData..ctor(String dir, WIN32_FIND_DATA findData)

   at JBToolkit.Windows.FastDirectoryEnumerator.FileEnumerator.get_Current()

   at YTMusicUploader.Business.FileScanner.Process()

   at YTMusicUploader.MainForm.MainProcess(Boolean restarting)</StackTrace>

    <Id>8344</Id>

  </YTMUploader-Log>
```

Thanks,
--
kurai

**Comment by jamesbrindle** [comment]
Hey, I'm near sure I've seen that before...

It's probably a corrupt file or something Dodgy with the file date and time
apparently.

I can possibly work around around it... Would be good to identify the file
though but I'll see what I can do.

Regards,

Jamie

**Comment by kuraikaze** [comment]
Appreciate it ;)

Indeed, nearly all the references I can find to the error seem to be people asking for help when their application bombs out when trying to parse a file with invalid date metadata.

Unfortunately I can't seem to find a simple app or method to programatically search my Music datastore and flag dodgy files.

**Comment by jamesbrindle** [comment]
How about looking for a file with 0 bytes?

**Comment by kuraikaze** [comment]
I did consider that - there are a few "placeholder" zero byte files that I have in the filesystem.  I wondered if one of the intermediate .NET updates that had been installed since I last used YTMU were objecting to those.
Removed the files to test, but same issue.

I've since poked around with WizTree and found the way to list the entire filesystem tree for the Music directory.
No unexpected zero byte files or strange dates found.

**Comment by kuraikaze** [comment]
Hrmmm - looks like it *was* a corrupt file and/or it's metadata somewhere.
I added and then removed the Archive attribute recursively on the whole share's filesystem to force a rewrite of the metadata & access times.
YTMU is now working 100% once again :)

Sorry for wasting your time with an issue that was entirely on my end.

**Comment by jamesbrindle** [comment]
Wow,

No you haven't wasted my time. I'm glad you got it working...

I'll still try and come up with a workaround and try create a bad file to
replicate and then handle the error.

Good work!

Cheers,

Jamie
