### ISSUE TITLE
Closing the Application Doesn't Remove it from Alt+Tab List

### ISSUE THREAD

**Issue by xcjs** [jamesbrindle/YTMusicUploader#4]
Even after clicking the "X" with the application minimizing to the system tray, it still shows up in the Alt+Tab list. 

I would expect the application to not show up in the Alt+Tab list when the window isn't visible.

**Comment by jamesbrindle** [comment]
I believe you're right. I don't think the app should show on 'Alt+Tab' I'll look into that!

**Comment by jamesbrindle** [comment]
Hi, this has now been resolved in the lastest version: [https://github.com/jamesbrindle/YTMusicUploader/releases](https://github.com/jamesbrindle/YTMusicUploader/releases).

Thank you reporting this BTW - Much appreciated.
